trigger:
  branches:
    include:
      - main  # Replace with your branch name if different

pool:
  name: new-pool  # Name of the agent pool
  demands:
    - maven  # Ensure the agent has Maven installed
    - Agent.Version -gtVersion 2.144.0  # Ensure the agent version is greater than 2.144.0

steps:  # Add the 'steps' key to group tasks
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'