trigger:
  branches:
    include:
      - main  # Replace with your branch name if different

pool:
  name: new-pool  # Name of the agent pool
  demands:
    - maven  # This ensures that the agent has Maven installed
    - Agent.Version -gtVersion 2.144.0  # Ensure the agent version is greater than 2.144.0

steps:
  - task: MavenTool@0
    inputs:
      versionSpec: '3.x'  # Specify the Maven version (you can change this if needed)
      installMaven: true  # Automatically installs Maven if it's not already installed

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Path to your pom.xml file
      goals: 'clean package'  # Goal to clean and build the package
      options: '-DskipTests=true'  # Optional: skip tests if not needed in the build

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**/*.jar'  # Copy all JAR files
      TargetFolder: '$(Build.ArtifactStagingDirectory)/output'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/output'
      ArtifactName: 'calculator-artifact'  # Name of the artifact
      publishLocation: 'Container'  # Publish to build artifacts container
